import Head from "next/head";
import MkSearchbox from "../components/mk-searchbox/mk-searchbox";
import { useState } from "react";
import MkComment from "../components/mk-comment/mk-comment";

export default function Home() {
  const [comments, setComments] = useState([]);
  return (
    <div className="flex flex-col h-screen justify-between align-center ml-5 mr-5 mx-auto ">
      <Head>
        <title>Mk searchbox App</title>
        <meta
          name="description"
          content="This is mk searchbox app generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto">
        <h1 className="text-center">Welcome to MK searchbox</h1>
        <MkSearchbox
          placeholder="Search in name,email or body..."
          setComments={setComments}
        ></MkSearchbox>
        <div className="mt-10 flex flex-col m-auto w-[70%]">
          {comments.map((comment, id) => (
            <MkComment
              key={id}
              name={comment.name}
              email={comment.email}
              body={comment.body}
            />
          ))}
        </div>
      </main>

      <footer className="text-center mb-10 bottom-0">
        Created by{" "}
        <a
          className="text-red-400 font-bold hover:text-slate-700"
          href="https://www.linkedin.com/in/marco-casto/"
          target="_blank"
          rel="noopener noreferrer"
        >
          mk
        </a>
      </footer>
    </div>
  );
}
